# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFirsttest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_firsttest(self):
    self.driver.get("https://insat.rnu.tn/")
    self.driver.set_window_size(1246, 812)
    self.driver.find_element(By.CSS_SELECTOR, ".cursor-pointer:nth-child(3) > .mr-3 > .text-center").click()
    self.driver.find_element(By.LINK_TEXT, "Toutes les actualités").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".max-w-md:nth-child(2) .text-2xl").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".hover\\3Atext-primary-300:nth-child(9)").click()
    self.driver.execute_script("window.scrollTo(0,0)")
  
